"""add_password_reset_to_users

Revision ID: f53a04e4f3a5
Revises: 7180de5bbe3b
Create Date: 2026-07-07 15:04:57.795544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53a04e4f3a5'
down_revision: Union[str, Sequence[str], None] = '7180de5bbe3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
