"""add_instructor_name_to_courses

Revision ID: 45778984d7f8
Revises: f53a04e4f3a5
Create Date: 2026-07-08 11:43:17.498901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45778984d7f8'
down_revision: Union[str, Sequence[str], None] = 'f53a04e4f3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('instructor_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'instructor_name')
    # ### end Alembic commands ###
