"""add attendance columns to courses

Revision ID: 9958173ee0f6
Revises: 912e74791ce6
Create Date: 2026-08-03 14:48:12.734660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9958173ee0f6'
down_revision: Union[str, Sequence[str], None] = '912e74791ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_class_cancellations_id'), 'class_cancellations', ['id'], unique=False)
    op.add_column('courses', sa.Column('attendance_cutoff_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'attendance_cutoff_time')
    op.drop_index(op.f('ix_class_cancellations_id'), table_name='class_cancellations')
    # ### end Alembic commands ###
