"""add unique constraints to enrollment and lesson_progress

Revision ID: bde15eceb75c
Revises: 409f72bbe43a
Create Date: 2026-07-08 13:11:26.361603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde15eceb75c'
down_revision: Union[str, Sequence[str], None] = '409f72bbe43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_enrollment_per_user_course', 'enrollments', ['user_id', 'course_id'])
    op.create_unique_constraint('uq_progress_per_enrollment_lesson', 'lesson_progress', ['enrollment_id', 'lesson_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_progress_per_enrollment_lesson', 'lesson_progress', type_='unique')
    op.drop_constraint('uq_enrollment_per_user_course', 'enrollments', type_='unique')
    # ### end Alembic commands ###
