"""Add thumbnail_url to lessons table

Revision ID: fbe63089d357
Revises: 9a63b4f07557
Create Date: 2026-07-28 13:34:18.268129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe63089d357'
down_revision: Union[str, Sequence[str], None] = '9a63b4f07557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('lessons', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.alter_column('users', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('lessons', 'thumbnail_url')
    # ### end Alembic commands ###
